<?php

namespace Database\Seeders;

use App\Models\User;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use App\Models\Usuario;
use App\Models\Materia;
use App\Models\Grupo;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {

        // User::factory(10)->create();

        User::factory()->create([
            'name' => 'Test User',
            'email' => 'test@example.com',
        ]);

        $now = Carbon::now();

        $carreras = [
            ['cve_carrera' => 2, 'area' => 0, 'tipo' => 'FACULTAD', 'carrera' => 'FACULTAD DE INGENIERÍA', 'nivel_max' => 10, 'columna_max' => 10],
            ['cve_carrera' => 41, 'area' => 3, 'tipo' => 'LICENCIATURA', 'carrera' => 'SEMESTRE PROPEDÉUTICO DE INGENIERÍA CIVIL', 'nivel_max' => 10, 'columna_max' => 10],
            ['cve_carrera' => 42, 'area' => 4, 'tipo' => 'LICENCIATURA', 'carrera' => 'SEMESTRE PROPEDÉUTICO DE INGENIERÍA EN GEOLOGÍA', 'nivel_max' => 10, 'columna_max' => 10],
            ['cve_carrera' => 43, 'area' => 5, 'tipo' => 'LICENCIATURA', 'carrera' => 'SEMESTRE PROPEDÉUTICO DE INGENIERÍA MECÁNICA ELÉCTRICA', 'nivel_max' => 10, 'columna_max' => 10],
            ['cve_carrera' => 44, 'area' => 7, 'tipo' => 'LICENCIATURA', 'carrera' => 'SEMESTRE PROPEDÉUTICO DE INGENIERÍA AGROINDUSTRIAL', 'nivel_max' => 10, 'columna_max' => 10],
            ['cve_carrera' => 45, 'area' => 5, 'tipo' => 'LICENCIATURA', 'carrera' => 'SEMESTRE PROPEDÉUTICO DE INGENIERÍA MECÁNICA ADMINISTRATIVA', 'nivel_max' => 10, 'columna_max' => 10],
            ['cve_carrera' => 46, 'area' => 5, 'tipo' => 'LICENCIATURA', 'carrera' => 'SEMESTRE PROPEDÉUTICO DE INGENIERÍA MECÁNICA', 'nivel_max' => 10, 'columna_max' => 10],
            ['cve_carrera' => 47, 'area' => 8, 'tipo' => 'LICENCIATURA', 'carrera' => 'SEMESTRE PROPEDÉUTICO DE INGENIERÍA EN COMPUTACIÓN', 'nivel_max' => 10, 'columna_max' => 10],
            ['cve_carrera' => 48, 'area' => 6, 'tipo' => 'LICENCIATURA', 'carrera' => 'SEMESTRE PROPEDÉUTICO DE INGENIERÍA METALÚRGICA Y TRANSFORMACIÓN', 'nivel_max' => 10, 'columna_max' => 10],
            ['cve_carrera' => 49, 'area' => 10, 'tipo' => 'LICENCIATURA', 'carrera' => 'SEMESTRE PROPEDÉUTICO DE INGENIERÍA AMBIENTAL', 'nivel_max' => 10, 'columna_max' => 10],
            ['cve_carrera' => 50, 'area' => 5, 'tipo' => 'LICENCIATURA', 'carrera' => 'SEMESTRE PROPEDÉUTICO DE INGENIERÍA EN ELECTRICIDAD', 'nivel_max' => 10, 'columna_max' => 10],
            ['cve_carrera' => 51, 'area' => 5, 'tipo' => 'LICENCIATURA', 'carrera' => 'SEMESTRE PROPEDÉUTICO DE INGENIERÍA EN MECATRÓNICA', 'nivel_max' => 10, 'columna_max' => 10],
            ['cve_carrera' => 52, 'area' => 3, 'tipo' => 'LICENCIATURA', 'carrera' => 'SEMESTRE PROPEDÉUTICO DE INGENIERÍA EN TOPOGRAFÍA', 'nivel_max' => 10, 'columna_max' => 10],
            ['cve_carrera' => 53, 'area' => 3, 'tipo' => 'LICENCIATURA', 'carrera' => 'SEMESTRE PROPEDÉUTICO DE INGENIERÍA EN GEOFIRMÁTICA', 'nivel_max' => 10, 'columna_max' => 10],
            ['cve_carrera' => 54, 'area' => 2, 'tipo' => 'LICENCIATURA', 'carrera' => 'SEMESTRE PROPEDÉUTICO DE INGENIERÍA EN SISTEMAS INFORMÁTICOS', 'nivel_max' => 10, 'columna_max' => 11],
            ['cve_carrera' => 63, 'area' => 3, 'tipo' => 'LICENCIATURA', 'carrera' => 'INGENIERÍA CIVIL', 'nivel_max' => 10, 'columna_max' => 10],
            ['cve_carrera' => 64, 'area' => 4, 'tipo' => 'LICENCIATURA', 'carrera' => 'INGENIERÍA EN GEOLOGÍA', 'nivel_max' => 9, 'columna_max' => 9],
            ['cve_carrera' => 65, 'area' => 5, 'tipo' => 'LICENCIATURA', 'carrera' => 'INGENIERÍA MECÁNICA ELÉCTRICA', 'nivel_max' => 10, 'columna_max' => 10],
            ['cve_carrera' => 68, 'area' => 7, 'tipo' => 'LICENCIATURA', 'carrera' => 'INGENIERÍA AGROINDUSTRIAL', 'nivel_max' => 10, 'columna_max' => 10],
            ['cve_carrera' => 69, 'area' => 5, 'tipo' => 'LICENCIATURA', 'carrera' => 'INGENIERÍA MECÁNICA ADMINISTRATIVA', 'nivel_max' => 10, 'columna_max' => 10],
            ['cve_carrera' => 71, 'area' => 5, 'tipo' => 'LICENCIATURA', 'carrera' => 'INGENIERO ELECTRICISTA', 'nivel_max' => 10, 'columna_max' => 10],
            ['cve_carrera' => 72, 'area' => 5, 'tipo' => 'LICENCIATURA', 'carrera' => 'INGENIERÍA MECÁNICA', 'nivel_max' => 10, 'columna_max' => 10],
            ['cve_carrera' => 73, 'area' => 6, 'tipo' => 'LICENCIATURA', 'carrera' => 'INGENIERÍA METALURGISTA DE TRANSFORMACIÓN', 'nivel_max' => 10, 'columna_max' => 10],
            ['cve_carrera' => 74, 'area' => 2, 'tipo' => 'LICENCIATURA', 'carrera' => 'INGENIERÍA EN INFORMÁTICA', 'nivel_max' => 10, 'columna_max' => 8],
            ['cve_carrera' => 75, 'area' => 2, 'tipo' => 'LICENCIATURA', 'carrera' => 'INGENIERÍA EN COMPUTACIÓN', 'nivel_max' => 10, 'columna_max' => 10],
        ];

        foreach ($carreras as &$carrera) {
            $carrera['created_at'] = $now;
            $carrera['updated_at'] = $now;
        }

        DB::table('carreras')->insert($carreras);

        $materias = [
            ['Robótica', 4, 0, 8, '2974'],
            ['Sistemas Embebidos', 4, 2, 10, '2985'],
            ['Automatización', 4, 0, 8, '2986'],
            ['Control Digital', 4, 0, 8, '2987'],
            ['Interfaces Digitales de Comunicación', 4, 0, 8, '2988'],

            ['Principios de Cómputo en la Nube', 4, 0, 8, '2841'],
            ['Administración de Redes', 4, 0, 8, '2824'],
            ['Arquitectura de Nube', 4, 0, 8, '2842'],
            ['Interacción de Redes', 4, 0, 8, '2829'],
            ['Servicios en la Nube', 4, 0, 8, '2843'],
            ['Modelado y Simulación de Redes', 4, 0, 8, '2827'],

            ['Fundamentos de Desarrollo Web', 4, 0, 8, '2238'],
            ['Fundamentos de Desarrollo Móvil', 4, 0, 8, '2239'],
            ['Aplicaciones Web Interactivas', 4, 0, 8, '2237'],
            ['Diseño de Interfaces', 4, 0, 8, '2244'],
            ['Aplicaciones Web Escalables', 4, 0, 8, '2245'],

            ['Introducción a los Sistemas Geoespaciales', 4, 0, 8, '2850'],
            ['Visión Computacional', 4, 0, 8, '2815'],
            ['Bases de Datos Geoespaciales', 4, 0, 8, '2851'],
            ['Geointeligencia Artificial Aplicada a la Teledetección', 4, 0, 8, '2852'],
            ['Geoaplicaciones Web y Móviles', 4, 0, 8, '2853'],
        ];

        foreach ($materias as $materia) {
            DB::table('materias_optativas')->insert([
                'nombreMateria' => $materia[0],
                'horasTeoria' => $materia[1],
                'horasPractica' => $materia[2],
                'creditos' => $materia[3],
                'claveMateria' => $materia[4],
                'claveCacei' => 'IA',
                'cve_carrera' => 75,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }

        Usuario::create([
            'rpe' => '1',
            'nombre' => 'Admin',
            'cve_carrera' => '75',
            'rol' => 1,
        ]);

        Grupo::create([
            'color' => '#000000',
            'created_at' => now(),
            'updated_at' => now(),
        ]);



        $this->seedMaterias();
    }

    protected function seedMaterias(): void
    {
        $now = now();
        DB::table('materias')->insert([
            // 1. Química A
            [
                'nombreMateria' => 'Química A',
                'horasTeoria'   => 3,
                'horasPractica' => 2,
                'creditos'      => 8,
                'claveMateria'  => '0071',
                'claveCacei'    => 'CB',
                'cve_Carrera'   => 75,
                'grupo_id'      => 1,
                'tipoMateria' => 'dfm',
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            // 2. Matemáticas Discretas I
            [
                'nombreMateria' => 'Matemáticas Discretas I',
                'horasTeoria'   => 4,
                'horasPractica' => 0,
                'creditos'      => 8,
                'claveMateria'  => '2151',
                'claveCacei'    => 'CB',
                'cve_Carrera'   => 75,
                'grupo_id'      => 1,
                'tipoMateria' => 'carrera',
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            // 3. Pensamiento Algoritmico
            [
                'nombreMateria' => 'Pensamiento Algorítmico',
                'horasTeoria'   => 4,
                'horasPractica' => 0,
                'creditos'      => 8,
                'claveMateria'  => '2229',
                'claveCacei'    => 'CI',
                'cve_Carrera'   => 75,
                'grupo_id'      => 1,
                'tipoMateria' => 'carrera',
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            // 4. Temas Selectos de Matemáticas
            [
                'nombreMateria' => 'Temas Selectos de Matemáticas',
                'horasTeoria'   => 4,
                'horasPractica' => 0,
                'creditos'      => 8,
                'claveMateria'  => '2150',
                'claveCacei'    => 'CB',
                'cve_Carrera'   => 75,
                'grupo_id'      => 1,
                'tipoMateria' => 'carrera',
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            // 5. Herramientas de Software
            [
                'nombreMateria' => 'Herramientas de Software',
                'horasTeoria'   => 4,
                'horasPractica' => 0,
                'creditos'      => 8,
                'claveMateria'  => '2805',
                'claveCacei'    => 'IA',
                'cve_Carrera'   => 75,
                'grupo_id'      => 1,
                'tipoMateria' => 'carrera',
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            // 6. Metodología de la Investigación
            [
                'nombreMateria' => 'Metodología de la Investigación',
                'horasTeoria'   => 0,
                'horasPractica' => 4,
                'creditos'      => 4,
                'claveMateria'  => '1005',
                'claveCacei'    => 'CS',
                'cve_Carrera'   => 75,
                'grupo_id'      => 1,
                'tipoMateria' => 'common',
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            // 7. Seminario de Orientación a Computación
            [
                'nombreMateria' => 'Seminario de Orientación a Computación',
                'horasTeoria'   => 0,
                'horasPractica' => 2,
                'creditos'      => 2,
                'claveMateria'  => '2002',
                'claveCacei'    => 'CC',
                'cve_Carrera'   => 75,
                'grupo_id'      => 1,
                'tipoMateria' => 'carrera',
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            // 8. Cálculo A
            [
                'nombreMateria' => 'Cálculo A',
                'horasTeoria'   => 3,
                'horasPractica' => 2,
                'creditos'      => 8,
                'claveMateria'  => '0051',
                'claveCacei'    => 'CB',
                'cve_Carrera'   => 75,
                'grupo_id'      => 1,
                'tipoMateria' => 'dfm',
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            // 9. Matemáticas Discretas II
            [
                'nombreMateria' => 'Matemáticas Discretas II',
                'horasTeoria'   => 4,
                'horasPractica' => 0,
                'creditos'      => 8,
                'claveMateria'  => '2152',
                'claveCacei'    => 'CB',
                'cve_Carrera'   => 75,
                'grupo_id'      => 1,
                'tipoMateria' => 'carrera',
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            // 10. Estructuras de Datos I
            [
                'nombreMateria' => 'Estructuras de Datos I',
                'horasTeoria'   => 4,
                'horasPractica' => 0,
                'creditos'      => 8,
                'claveMateria'  => '2231',
                'claveCacei'    => 'CI',
                'cve_Carrera'   => 75,
                'grupo_id'      => 1,
                'tipoMateria' => 'carrera',
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            // 11. Álgebra B
            [
                'nombreMateria' => 'Álgebra B',
                'horasTeoria'   => 3,
                'horasPractica' => 2,
                'creditos'      => 8,
                'claveMateria'  => '0042',
                'claveCacei'    => 'CB',
                'cve_Carrera'   => 75,
                'grupo_id'      => 1,
                'tipoMateria' => 'dfm',
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            // 12. Fundamentos de Circuitos Eléctricos
            [
                'nombreMateria' => 'Fundamentos de Circuitos Eléctricos',
                'horasTeoria'   => 4,
                'horasPractica' => 2,
                'creditos'      => 10,
                'claveMateria'  => '2978',
                'claveCacei'    => 'CI',
                'cve_Carrera'   => 75,
                'grupo_id'      => 1,
                'tipoMateria' => 'carrera',
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            // 13. Inglés 1
            [
                'nombreMateria' => 'Inglés 1',
                'horasTeoria'   => 0,
                'horasPractica' => 5,
                'creditos'      => 5,
                'claveMateria'  => '1936',
                'claveCacei'    => 'CC',
                'cve_Carrera'   => 75,
                'grupo_id'      => 1,
                'tipoMateria' => 'ing',
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            // 14. Cálculo B
            [
                'nombreMateria' => 'Cálculo B',
                'horasTeoria'   => 3,
                'horasPractica' => 2,
                'creditos'      => 8,
                'claveMateria'  => '0052',
                'claveCacei'    => 'CB',
                'cve_Carrera'   => 75,
                'grupo_id'      => 1,
                'tipoMateria' => 'dfm',
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            // 15. Ingeniería de Software
            [
                'nombreMateria' => 'Ingeniería de Software',
                'horasTeoria'   => 4,
                'horasPractica' => 0,
                'creditos'      => 8,
                'claveMateria'  => '2304',
                'claveCacei'    => 'IA',
                'cve_Carrera'   => 75,
                'grupo_id'      => 1,
                'tipoMateria' => 'carrera',
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            // 16. Estructuras de Datos II
            [
                'nombreMateria' => 'Estructuras de Datos II',
                'horasTeoria'   => 4,
                'horasPractica' => 0,
                'creditos'      => 8,
                'claveMateria'  => '2232',
                'claveCacei'    => 'CI',
                'cve_Carrera'   => 75,
                'grupo_id'      => 1,
                'tipoMateria' => 'carrera',
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            // 17. Lenguajes de Programación
            [
                'nombreMateria' => 'Lenguajes de Programación',
                'horasTeoria'   => 4,
                'horasPractica' => 0,
                'creditos'      => 8,
                'claveMateria'  => '2233',
                'claveCacei'    => 'CI',
                'cve_Carrera'   => 75,
                'grupo_id'      => 1,
                'tipoMateria' => 'carrera',
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            // 18. Dispositivos Semiconductores
            [
                'nombreMateria' => 'Dispositivos Semiconductores',
                'horasTeoria'   => 4,
                'horasPractica' => 2,
                'creditos'      => 10,
                'claveMateria'  => '2979',
                'claveCacei'    => 'CI',
                'cve_Carrera'   => 75,
                'grupo_id'      => 1,
                'tipoMateria' => 'carrera',
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            // 19. Tendencias Sociales
            [
                'nombreMateria' => 'Tendencias Sociales',
                'horasTeoria'   => 0,
                'horasPractica' => 2,
                'creditos'      => 2,
                'claveMateria'  => '1008',
                'claveCacei'    => 'CS',
                'cve_Carrera'   => 75,
                'grupo_id'      => 1,
                'tipoMateria' => 'common',
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            // 20. Cálculo D
            [
                'nombreMateria' => 'Cálculo D',
                'horasTeoria'   => 3,
                'horasPractica' => 2,
                'creditos'      => 8,
                'claveMateria'  => '0054',
                'claveCacei'    => 'CB',
                'cve_Carrera'   => 75,
                'grupo_id'      => 1,
                'tipoMateria' => 'dfm',
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            // 21. Tecnología Orientada a Objetos
            [
                'nombreMateria' => 'Tecnología Orientada a Objetos',
                'horasTeoria'   => 4,
                'horasPractica' => 0,
                'creditos'      => 8,
                'claveMateria'  => '2234',
                'claveCacei'    => 'IA',
                'cve_Carrera'   => 75,
                'grupo_id'      => 1,
                'tipoMateria' => 'carrera',
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            // 22. Algoritmos y Complejidad
            [
                'nombreMateria' => 'Algoritmos y Complejidad',
                'horasTeoria'   => 4,
                'horasPractica' => 0,
                'creditos'      => 8,
                'claveMateria'  => '2235',
                'claveCacei'    => 'CI',
                'cve_Carrera'   => 75,
                'grupo_id'      => 1,
                'tipoMateria' => 'carrera',
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            // 23. Bases de Datos
            [
                'nombreMateria' => 'Bases de Datos',
                'horasTeoria'   => 4,
                'horasPractica' => 0,
                'creditos'      => 8,
                'claveMateria'  => '2314',
                'claveCacei'    => 'IA',
                'cve_Carrera'   => 75,
                'grupo_id'      => 1,
                'tipoMateria' => 'carrera',
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            // 24. Fundamentos de Diseño Digital
            [
                'nombreMateria' => 'Fundamentos de Diseño Digital',
                'horasTeoria'   => 4,
                'horasPractica' => 2,
                'creditos'      => 10,
                'claveMateria'  => '2977',
                'claveCacei'    => 'IA',
                'cve_Carrera'   => 75,
                'grupo_id'      => 1,
                'tipoMateria' => 'carrera',
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            // 25. Gestión y Desarrollo Social
            [
                'nombreMateria' => 'Gestión y Desarrollo Social',
                'horasTeoria'   => 0,
                'horasPractica' => 2,
                'creditos'      => 2,
                'claveMateria'  => '1009',
                'claveCacei'    => 'CS',
                'cve_Carrera'   => 75,
                'grupo_id'      => 1,
                'tipoMateria' => 'common',
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            // 26. Inglés 2
            [
                'nombreMateria' => 'Inglés 2',
                'horasTeoria'   => 0,
                'horasPractica' => 5,
                'creditos'      => 5,
                'claveMateria'  => '1937',
                'claveCacei'    => 'CC',
                'cve_Carrera'   => 75,
                'grupo_id'      => 1,
                'tipoMateria' => 'ing',
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            // 27. Análisis Numérico
            [
                'nombreMateria' => 'Análisis Numérico',
                'horasTeoria'   => 4,
                'horasPractica' => 0,
                'creditos'      => 8,
                'claveMateria'  => '2111',
                'claveCacei'    => 'CB',
                'cve_Carrera'   => 75,
                'grupo_id'      => 1,
                'tipoMateria' => 'carrera',
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            // 28. Interfaces Gráficas con Aplicaciones
            [
                'nombreMateria' => 'Interfaces Gráficas con Aplicaciones',
                'horasTeoria'   => 4,
                'horasPractica' => 0,
                'creditos'      => 8,
                'claveMateria'  => '2236',
                'claveCacei'    => 'IA',
                'cve_Carrera'   => 75,
                'grupo_id'      => 1,
                'tipoMateria' => 'carrera',
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            // 29. Gestión de Servidores y Seguridad
            [
                'nombreMateria' => 'Gestión de Servidores y Seguridad',
                'horasTeoria'   => 4,
                'horasPractica' => 0,
                'creditos'      => 8,
                'claveMateria'  => '2840',
                'claveCacei'    => 'CI',
                'cve_Carrera'   => 75,
                'grupo_id'      => 1,
                'tipoMateria' => 'carrera',
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            // 30. Física A
            [
                'nombreMateria' => 'Física A',
                'horasTeoria'   => 3,
                'horasPractica' => 2,
                'creditos'      => 8,
                'claveMateria'  => '0061',
                'claveCacei'    => 'CI',
                'cve_Carrera'   => 75,
                'grupo_id'      => 1,
                'tipoMateria' => 'dfm',
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            // 31. Diseño Digital
            [
                'nombreMateria' => 'Diseño Digital',
                'horasTeoria'   => 4,
                'horasPractica' => 2,
                'creditos'      => 10,
                'claveMateria'  => '2980',
                'claveCacei'    => 'IA',
                'cve_Carrera'   => 75,
                'grupo_id'      => 1,
                'tipoMateria' => 'carrera',
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            // 32. Act. Artísticas, Deportivas o de Divulgación
            [
                'nombreMateria' => 'Act. Artísticas, Deportivas o de Divulgación',
                'horasTeoria'   => 0,
                'horasPractica' => 2,
                'creditos'      => 2,
                'claveMateria'  => '1014',
                'claveCacei'    => 'CS',
                'cve_Carrera'   => 75,
                'grupo_id'      => 1,
                'tipoMateria' => 'common',
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            // 33. Inglés 3
            [
                'nombreMateria' => 'Inglés 3',
                'horasTeoria'   => 0,
                'horasPractica' => 5,
                'creditos'      => 5,
                'claveMateria'  => '1938',
                'claveCacei'    => 'CC',
                'cve_Carrera'   => 75,
                'grupo_id'      => 1,
                'tipoMateria' => 'ing',
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            // 34. Probabilidad y Estadística
            [
                'nombreMateria' => 'Probabilidad y Estadística',
                'horasTeoria'   => 4,
                'horasPractica' => 0,
                'creditos'      => 8,
                'claveMateria'  => '2112',
                'claveCacei'    => 'CB',
                'cve_Carrera'   => 75,
                'grupo_id'      => 1,
                'tipoMateria' => 'carrera',
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            // 35. Estructuras de Datos Avanzadas
            [
                'nombreMateria' => 'Estructuras de Datos Avanzadas',
                'horasTeoria'   => 4,
                'horasPractica' => 0,
                'creditos'      => 8,
                'claveMateria'  => '2206',
                'claveCacei'    => 'CI',
                'cve_Carrera'   => 75,
                'grupo_id'      => 1,
                'tipoMateria' => 'carrera',
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            // 36. Diseño e Implementación de Redes
            [
                'nombreMateria' => 'Diseño e Implementación de Redes',
                'horasTeoria'   => 4,
                'horasPractica' => 0,
                'creditos'      => 8,
                'claveMateria'  => '2823',
                'claveCacei'    => 'CI',
                'cve_Carrera'   => 75,
                'grupo_id'      => 1,
                'tipoMateria' => 'carrera',
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            // 37. Sistemas Operativos
            [
                'nombreMateria' => 'Sistemas Operativos',
                'horasTeoria'   => 4,
                'horasPractica' => 0,
                'creditos'      => 8,
                'claveMateria'  => '2252',
                'claveCacei'    => 'CI',
                'cve_Carrera'   => 75,
                'grupo_id'      => 1,
                'tipoMateria' => 'carrera',
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            // 38. Diseño de Microcomputadoras
            [
                'nombreMateria' => 'Diseño de Microcomputadoras',
                'horasTeoria'   => 4,
                'horasPractica' => 0,
                'creditos'      => 8,
                'claveMateria'  => '2981',
                'claveCacei'    => 'IA',
                'cve_Carrera'   => 75,
                'grupo_id'      => 1,
                'tipoMateria' => 'carrera',
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            // 39. Arte, Cultura y Humanidades I
            [
                'nombreMateria' => 'Arte, Cultura y Humanidades I',
                'horasTeoria'   => 0,
                'horasPractica' => 2,
                'creditos'      => 2,
                'claveMateria'  => '1012',
                'claveCacei'    => 'CS',
                'cve_Carrera'   => 75,
                'grupo_id'      => 1,
                'tipoMateria' => 'common',
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            // 40. Inglés 4
            [
                'nombreMateria' => 'Inglés 4',
                'horasTeoria'   => 0,
                'horasPractica' => 5,
                'creditos'      => 5,
                'claveMateria'  => '1939',
                'claveCacei'    => 'CC',
                'cve_Carrera'   => 75,
                'grupo_id'      => 1,
                'tipoMateria' => 'common',
                'created_at'    => $now,
                'updated_at'    => $now,
            ],

            [
                'nombreMateria' => 'Seminario de Medio Término',
                'horasTeoria' => 0,
                'horasPractica' => 2,
                'creditos' => 2,
                'claveMateria' => '2008',
                'claveCacei' => 'CC',
                'cve_carrera' => 75,
                'grupo_id' => 1,
                'tipoMateria' => 'carrera',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombreMateria' => 'Administración de Proyectos I',
                'horasTeoria' => 4,
                'horasPractica' => 0,
                'creditos' => 8,
                'claveMateria' => '2053',
                'claveCacei' => 'CE',
                'cve_carrera' => 75,
                'grupo_id' => 1,
                'tipoMateria' => 'carrera',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombreMateria' => 'Fundamentos de Compiladores',
                'horasTeoria' => 4,
                'horasPractica' => 0,
                'creditos' => 8,
                'claveMateria' => '2408',
                'claveCacei' => 'CI',
                'cve_carrera' => 75,
                'grupo_id' => 1,
                'tipoMateria' => 'carrera',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombreMateria' => 'Electivas de Área de Énfasis',
                'horasTeoria' => 0,
                'horasPractica' => 0,
                'creditos' => 0,
                'claveMateria' => '',
                'claveCacei' => '',
                'cve_carrera' => 75,
                'grupo_id' => 1,
                'tipoMateria' => 'carrera',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombreMateria' => 'Microcontroladores',
                'horasTeoria' => 4,
                'horasPractica' => 0,
                'creditos' => 8,
                'claveMateria' => '2982',
                'claveCacei' => 'IA',
                'cve_carrera' => 75,
                'grupo_id' => 1,
                'tipoMateria' => 'carrera',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombreMateria' => 'Téc. de Comunicación Oral y Escrita',
                'horasTeoria' => 0,
                'horasPractica' => 5,
                'creditos' => 5,
                'claveMateria' => '1006',
                'claveCacei' => 'CC',
                'cve_carrera' => 75,
                'grupo_id' => 1,
                'tipoMateria' => 'common',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombreMateria' => 'Inglés 5',
                'horasTeoria' => 0,
                'horasPractica' => 5,
                'creditos' => 5,
                'claveMateria' => '1940',
                'claveCacei' => 'CC',
                'cve_carrera' => 75,
                'grupo_id' => 1,
                'tipoMateria' => 'ing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombreMateria' => 'Proyectos Computacionales I',
                'horasTeoria' => 4,
                'horasPractica' => 0,
                'creditos' => 8,
                'claveMateria' => '2050',
                'claveCacei' => 'IA',
                'cve_carrera' => 75,
                'grupo_id' => 1,
                'tipoMateria' => 'carrera',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombreMateria' => 'Administración de Proyectos II',
                'horasTeoria' => 4,
                'horasPractica' => 0,
                'creditos' => 8,
                'claveMateria' => '2054',
                'claveCacei' => 'CE',
                'cve_carrera' => 75,
                'grupo_id' => 1,
                'tipoMateria' => 'carrera',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombreMateria' => 'Actividades de Aprendizaje I',
                'horasTeoria' => 0,
                'horasPractica' => 2,
                'creditos' => 2,
                'claveMateria' => '1916',
                'claveCacei' => 'CC',
                'cve_carrera' => 75,
                'grupo_id' => 1,
                'tipoMateria' => 'common',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombreMateria' => 'Sistemas Operativos Avanzados',
                'horasTeoria' => 4,
                'horasPractica' => 0,
                'creditos' => 8,
                'claveMateria' => '2405',
                'claveCacei' => 'IA',
                'cve_carrera' => 75,
                'grupo_id' => 1,
                'tipoMateria' => 'carrera',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombreMateria' => 'Procesamiento de Señales',
                'horasTeoria' => 4,
                'horasPractica' => 0,
                'creditos' => 8,
                'claveMateria' => '2984',
                'claveCacei' => 'CI',
                'cve_carrera' => 75,
                'grupo_id' => 1,
                'tipoMateria' => 'carrera',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombreMateria' => 'Movilidad I',
                'horasTeoria' => 0,
                'horasPractica' => 3,
                'creditos' => 6,
                'claveMateria' => '1908',
                'claveCacei' => 'CC',
                'cve_carrera' => 75,
                'grupo_id' => 1,
                'tipoMateria' => 'common',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombreMateria' => 'Liderazgo',
                'horasTeoria' => 0,
                'horasPractica' => 2,
                'creditos' => 2,
                'claveMateria' => '1015',
                'claveCacei' => 'CS',
                'cve_carrera' => 75,
                'grupo_id' => 1,
                'tipoMateria' => 'common',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombreMateria' => 'Proyectos Computacionales II',
                'horasTeoria' => 4,
                'horasPractica' => 0,
                'creditos' => 8,
                'claveMateria' => '2051',
                'claveCacei' => 'CE',
                'cve_carrera' => 75,
                'grupo_id' => 1,
                'tipoMateria' => 'carrera',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombreMateria' => 'Fundamentos de Inteligencia Artificial',
                'horasTeoria' => 4,
                'horasPractica' => 0,
                'creditos' => 8,
                'claveMateria' => '2813',
                'claveCacei' => 'IA',
                'cve_carrera' => 75,
                'grupo_id' => 1,
                'tipoMateria' => 'carrera',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombreMateria' => 'Fundamentos de Software de Sistemas',
                'horasTeoria' => 4,
                'horasPractica' => 0,
                'creditos' => 8,
                'claveMateria' => '2409',
                'claveCacei' => 'CI',
                'cve_carrera' => 75,
                'grupo_id' => 1,
                'tipoMateria' => 'carrera',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombreMateria' => 'Administración de Bases de Datos',
                'horasTeoria' => 3,
                'horasPractica' => 2,
                'creditos' => 8,
                'claveMateria' => '2313',
                'claveCacei' => 'CI',
                'cve_carrera' => 75,
                'grupo_id' => 1,
                'tipoMateria' => 'carrera',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombreMateria' => 'Supercómputo',
                'horasTeoria' => 0,
                'horasPractica' => 8,
                'creditos' => 8,
                'claveMateria' => '2228',
                'claveCacei' => 'IA',
                'cve_carrera' => 75,
                'grupo_id' => 1,
                'tipoMateria' => 'carrera',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombreMateria' => 'Prácticas Profesionales COMP',
                'horasTeoria' => 0,
                'horasPractica' => 15,
                'creditos' => 15,
                'claveMateria' => '2007',
                'claveCacei' => 'IA',
                'cve_carrera' => 75,
                'grupo_id' => 1,
                'tipoMateria' => 'carrera',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombreMateria' => 'Emprendimiento',
                'horasTeoria' => 0,
                'horasPractica' => 2,
                'creditos' => 2,
                'claveMateria' => '1016',
                'claveCacei' => 'CS',
                'cve_carrera' => 75,
                'grupo_id' => 1,
                'tipoMateria' => 'common',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombreMateria' => 'Proyectos Computacionales III',
                'horasTeoria' => 4,
                'horasPractica' => 0,
                'creditos' => 8,
                'claveMateria' => '2052',
                'claveCacei' => 'CE',
                'cve_carrera' => 75,
                'grupo_id' => 1,
                'tipoMateria' => 'carrera',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombreMateria' => 'Seminario de Egreso',
                'horasTeoria' => 0,
                'horasPractica' => 0,
                'creditos' => 0,
                'claveMateria' => '1926',
                'claveCacei' => 'CC',
                'cve_carrera' => 75,
                'grupo_id' => 1,
                'tipoMateria' => 'common',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombreMateria' => 'Computación y Sociedad',
                'horasTeoria' => 0,
                'horasPractica' => 2,
                'creditos' => 2,
                'claveMateria' => '2085',
                'claveCacei' => 'CC',
                'cve_carrera' => 75,
                'grupo_id' => 1,
                'tipoMateria' => 'carrera',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombreMateria' => 'Arte, Cultura y Humanidades II',
                'horasTeoria' => 0,
                'horasPractica' => 2,
                'creditos' => 2,
                'claveMateria' => '1013',
                'claveCacei' => 'CS',
                'cve_carrera' => 75,
                'grupo_id' => 1,
                'tipoMateria' => 'common',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
